[webservers]
13.203.217.163

[webservers:vars]
# Tell Ansible to log in as the default Amazon Linux user
ansible_user=ec2-user

# Tell Ansible exactly where your secret key is
ansible_ssh_private_key_file=~/.ssh/my_aws_key

# Tell Ansible to ignore the initial SSH fingerprint warning
ansible_ssh_common_args='-o StrictHostKeyChecking=no'