---
- name: Configure Web Server
  hosts: all
  become: yes 
  vars:
    # Explicitly tell Ansible to use the modern Python 3 path
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure Apache (httpd) is installed
      # CHANGED: We are using 'dnf' instead of 'yum'
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Ensure Apache is running and starts on boot
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a custom index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <body style="background-color: #282c34; color: white; text-align: center; font-family: sans-serif; padding-top: 20%;">
              <h1>Deployed with ZERO Clicks using GitHub Webhooks!</h1>
              <p>This server was built by Terraform, configured by Ansible, and deployed via Jenkins and GitHub.</p>
            </body>
          </html>