---
- name: Configure Web Server
  hosts: all
  become: yes # This tells Ansible to use 'sudo' for root privileges

  tasks:
    - name: Ensure Apache (httpd) is installed
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and starts on boot
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Create a custom index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <body style="background-color: #282c34; color: white; text-align: center; font-family: sans-serif; padding-top: 20%;">
              <h1>Mission Accomplished!</h1>
              <p>This server was built by Terraform and configured by Ansible.</p>
            </body>
          </html>