---
- name: Deploy Dockerized Node.js App
  hosts: all
  become: yes 
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Start and Enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure app directory exists on the EC2 server
      ansible.builtin.file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy the Node.js app folder to the EC2 server
      ansible.builtin.copy:
        src: app/
        dest: /home/ec2-user/app/

    - name: Stop and remove the old container (if it exists)
      ansible.builtin.command: docker rm -f node-api
      ignore_errors: yes

    - name: Build the new Docker image
      ansible.builtin.command: docker build -t my-node-app .
      args:
        chdir: /home/ec2-user/app/

    - name: Run the Docker container
      ansible.builtin.command: docker run -d --name node-api -p 80:80 my-node-app